# Permalinks
permalink: pretty

# Setup
title: Soundlly
tagline: 'inspires your video viewers to mobile'
description: ''
url: https://soundlly.github.io
paginate: 5

# Plugins
plugins: [jekyll-paginate]

# GitHub
github:
  soundlly:
    url: https://github.com/Soundlly
  android:
    url: https://github.com/Soundlly/BitsoundSDK-Android
    version: v3.3.1
  ios:
    url: https://github.com/Soundlly/BitsoundSDK-iOS
    version: 2.1.1

# Authors
authors:
  pjhjohn:
    name: 박준호
    gravatar: 9ebc92b0e36b0c5d3f134aeee5c92096
    email: pjhjohn@soundl.ly
    github: pjhjohn
  humbledude:
    name: 박근희
    gravatar: ba40387f2f18e1e0c2164d111cbe0607
    email: keunhui.park@soundl.ly
    github: humbledude
